site_name: 'Footy Hub'
repo_name: 'cyuss/footy-hub'
repo_url: 'https://github.com/cyuss/footy-hub'
nav:
  - Home: 'index.md'
  - Usage: 'usage.md'
  - Data: 'data.md'
extra:
  social:
    - icon: fontawesome/brands/github-alt
      link: 'https://github.com/cyuss/footy-hub'
theme:
  name: 'material'
  icon:
    repo: fontawesome/brands/github-alt
  palette:
      # - primary: 'teal'
      # - accent: 'green'
      - media: "(prefers-color-scheme: light)"
        scheme: default
        primary: 'teal'
        accent: 'green'
        toggle:
          icon: material/weather-sunny
          name: Switch to dark mode
      - media: "(prefers-color-scheme: dark)"
        scheme: slate
        primary: 'teal'
        accent: 'green'
        toggle:
          icon: material/weather-night
          name: Switch to light mode
  features:
      # - navigation.tabs
      - navigation.top
  font:
      text: 'Roboto'
  # logo:
  #     icon: 'textsms'
  # icon:
  #     logo: 'textsms'
plugins:
  - search
  - tags
  # - mkdocstrings
  # - autorefs
  - minify:
      minify_html: true
  # - git-revision-date-localized
markdown_extensions:
  - admonition
  - codehilite
  - footnotes
  - meta
  - toc:
      permalink: true
  - pymdownx.arithmatex
  - pymdownx.betterem:
      smart_enable: all
  - pymdownx.caret
  - pymdownx.critic
  - pymdownx.details
  - pymdownx.tabbed
  # - pymdownx.emoji:
  #     emoji_generator: !!python/name:pymdownx.emoji.to_svg
  - pymdownx.inlinehilite
  - pymdownx.magiclink
  - pymdownx.mark
  - pymdownx.smartsymbols
  - pymdownx.highlight
  - pymdownx.superfences
  - pymdownx.tasklist:
      custom_checkbox: true
  - pymdownx.tilde
extra_javascript:
    - 'https://cdnjs.cloudflare.com/ajax/libs/mathjax/2.7.0/MathJax.js?config=TeX-MML-AM_CHTML'
